# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run iOS tests"
  lane :tests do
    sync_podspec_version_to_xcode()
    common_tests(scheme: "Backtrace-iOS-lib", disable_slide_to_type: true)
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
  end
end

platform :mac do
  desc "Run macOS tests"
  lane :tests do
    sync_podspec_version_to_xcode()
    common_tests(scheme: "Backtrace-macOS-lib", disable_slide_to_type: true)
  end
end

platform :tvos do
  desc "Run tvOS tests"
  lane :tests do
    sync_podspec_version_to_xcode()
    common_tests(scheme: "Backtrace-tvOS-lib")
  end
end

desc "Run tests"
lane :common_tests do |options|
  scan(
    workspace: "Backtrace.xcworkspace",
    scheme: options[:scheme],
    clean: false,
    code_coverage: true,
    open_report: true,
    disable_slide_to_type: options[:disable_slide_to_type],
    disable_concurrent_testing: true
  )
end

desc "Sync Podspec version to Xcode MARKETING_VERSION"
lane :sync_podspec_version_to_xcode do |options|
    version_number = version_get_podspec(path: "Backtrace.podspec")
    puts version_number
    sh("sed -i '' -e 's/MARKETING_VERSION \\= [^\\;]*\\;/MARKETING_VERSION = #{version_number};/' ../Backtrace.xcodeproj/project.pbxproj")
end