name: Deploy to Cocoapods

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  # test is copied pasted from test.yml - do in a clean way in the future
  # BEGIN COPY PASTE FROM TEST.YML
  test:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
          platform: [ios, mac, tvos]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sh scripts/install.sh
      - name: Run test
        run: fastlane ${{ matrix.platform }} tests
    
  pod-lint:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sh scripts/install.sh
  # END COPY PASTE FROM TEST.YML
  
  deploy-cocoapods:
    runs-on: macos-latest
    needs: [pod-lint, test]
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sh scripts/install.sh
      - name: Deploy to Cocoapods
        run: sh scripts/deploy.sh
        env:
         COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
