name: Deploy to Cocoapods

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sh scripts/install.sh
      - name: Run tests
        run: sh scripts/test.sh
      - name: Deploy to Cocoapods
        run: sh scripts/deploy.sh
        env:
         COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
