name: Run tests

on:
  push:
    branches: 
      - develop
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sh scripts/test.sh