name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [master, release]
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [ios, mac, tvos]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sh scripts/install.sh
      - name: Run test
        run: fastlane ${{ matrix.platform }} tests

  pod-lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sh scripts/install.sh
