name: Run tests

on: 
  workflow_dispatch:
  pull_request:
    branches: 
      - release
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:

  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
          platform: [ios, mac, tvos]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sh scripts/install.sh
      - name: Run test
        run: fastlane ${{ matrix.platform }} tests
    
  pod-lint:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sh scripts/install.sh
      - name: Run pod lib lint
        run: pod lib lint --verbose --allow-warnings --sources='https://cdn.cocoapods.org/'
  
